name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        name: "Upload Moxie Discord"
        with:
          name: Moxie Discord
          path: platforms/discord/build/libs/*-fat.jar
      - uses: actions/upload-artifact@v2
        name: "Upload Moxie Web"
        with:
          name: Moxie Web
          path: platforms/web/build/libs/*-fat.jar